<?php

/**
 * @file
 * Install, update and uninstall functions for the module.
 */

declare(strict_types=1);

/**
 * Install new submodule for hypermedia integration.
 */
function jsonapi_menu_items_update_8001(): void {
  if (\Drupal::moduleHandler()->moduleExists('jsonapi_hypermedia')) {
    \Drupal::service('module_installer')->install(['jsonapi_menu_items_hypermedia']);
  }
}

/**
 * Clear route resource type caches to adopt new lightweight cache format.
 */
function jsonapi_menu_items_update_8002(): void {
  \Drupal::service('cache_tags.invalidator')->invalidateTags(['jsonapi_resource_types']);
}
